/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author ignoi
 */
public class Browser extends javax.swing.JFrame {

    /**
     * Creates new form Browser
     */
    public Browser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        botaoIr = new javax.swing.JButton();
        caixaHistorico = new javax.swing.JComboBox();
        labelConteudo = new javax.swing.JLabel();
        jrOK = new javax.swing.JRadioButton();
        jrTIMED_OUT = new javax.swing.JRadioButton();
        jrBAD_GATEWAY = new javax.swing.JRadioButton();
        jrbUNAUTHORIZED = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoIr.setText("Ir");

        labelConteudo.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        labelConteudo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        buttonGroup1.add(jrOK);
        jrOK.setText("OK");

        buttonGroup1.add(jrTIMED_OUT);
        jrTIMED_OUT.setText("Sem Conexão");

        buttonGroup1.add(jrBAD_GATEWAY);
        jrBAD_GATEWAY.setText("Servidor Offline");

        buttonGroup1.add(jrbUNAUTHORIZED);
        jrbUNAUTHORIZED.setText("Autenticação Falhou");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrTIMED_OUT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrBAD_GATEWAY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbUNAUTHORIZED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(caixaHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoIr, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoIr))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrOK)
                    .addComponent(jrTIMED_OUT)
                    .addComponent(jrBAD_GATEWAY)
                    .addComponent(jrbUNAUTHORIZED))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botaoIr;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox caixaHistorico;
    public javax.swing.JRadioButton jrBAD_GATEWAY;
    public javax.swing.JRadioButton jrOK;
    public javax.swing.JRadioButton jrTIMED_OUT;
    public javax.swing.JRadioButton jrbUNAUTHORIZED;
    public javax.swing.JLabel labelConteudo;
    // End of variables declaration//GEN-END:variables
}
